### ISSUE TITLE
No Search Results Coming Up

### ISSUE THREAD

**Issue by burkhartpm** [djdembeck/Audnexus.bundle#100]
I installed this plug-in into Plex. It appears in the metadata agent list just fine, but no matter what I do, some sort of 404 error on the backend prevents any results from displaying. I've deleted caches, uninstalled and reinstalled the plugin, installed other versions, and tried installing it in the main Program Files Plex folder (and not just user Local AppData). Nothing has gotten this plug-in working. The built-in Plex metadata agents still work and I can see Audnexus results in my browser with direct API links (so it's not a firewall issue). Nothing has changed with my setup or networking. Can anyone please help me out with this? I've attached logs that might be helpful. 
[Plex Media Server.log](https://github.com/djdembeck/Audnexus.bundle/files/11408781/Plex.Media.Server.log)
[com.plexapp.agents.audnexus.log](https://github.com/djdembeck/Audnexus.bundle/files/11408788/com.plexapp.agents.audnexus.log)

**Comment by rabelux** [comment]
Have a look at #95

**Comment by burkhartpm** [comment]
Ugh. That does look like my issue. Thank you.  I see that no one on that thread answered whether Audnexus users will ever be able to update their PMS again. Do you know the answer to that question? Also, forgive the maybe silly question, but if I uninstall through the apps menu, won't that remove my user data as well? Will I have to rebuild my entire Plex server preferences and libraries?

**Comment by djdembeck** [comment]
Please see my response to the above-mentioned issue.
