### ISSUE TITLE
Agent Not visible in Plex Settings aftering installing 

### ISSUE THREAD

**Issue by DanielCalverley** [djdembeck/Audnexus.bundle#103]
I've followed the instructions listed. I've also restarted my plex server several times and even did a reboot for good mesure. The agent is not appearing. Any advice? 

**No Plugins Installed**
![image](https://github.com/djdembeck/Audnexus.bundle/assets/60716793/b8d7fb95-5e1c-45c7-966a-63684d566316)

**File Sctructure** 
![image](https://github.com/djdembeck/Audnexus.bundle/assets/60716793/7bd16021-1dd4-4560-999b-ff3e63a9da12)

Plex Status
![image](https://github.com/djdembeck/Audnexus.bundle/assets/60716793/e26cffc0-a3b5-48a3-a612-65a88f8d6a9c)
![image](https://github.com/djdembeck/Audnexus.bundle/assets/60716793/4f03b716-fe90-4d65-884e-6d3757e1c642)

**Comment by djdembeck** [comment]
https://github.com/djdembeck/Audnexus.bundle/issues/50
