### ISSUE TITLE
[Reqeust] Please create a `release` branch and follow your releases

### ISSUE THREAD

**Issue by urda** [djdembeck/Audnexus.bundle#104]
I would love to be able to just `git pull` the `releases` branch to have the "latest" release. This is preferred to a "detached head" state where users have to checkout the release tags.

It would be great if the repo owners would:

- Create a release off the latest release (v1.3.0 at time of issue creation) with `git checkout -b release` and push to GitHub.
- Update the `release` branch to the latest release every time a release is made.

**Comment by djdembeck** [comment]
all releases are staged in `develop` and then merged into `main` when a version is cut/released.

**Comment by urda** [comment]
Then why is `main` out of sync from `v1.3.0`? 

A user blindly pulling `main` will not get `v1.3.0` today.

```
$ git graph
* 8c940c6 Thu, 22 Jun 2023 17:03:09 -0500 (8 hours ago) [N] (origin/main, origin/develop, origin/HEAD, main)
| docs: :memo: add similar authors to list of data - djdembeck <dembeck.david@protonmail.com>
* 5e39601 Thu, 22 Jun 2023 16:58:45 -0500 (8 hours ago) [N] (HEAD -> urda/release, tag: v1.3.0)
| chore(release): 1.3.0 - djdembeck <dembeck.david@protonmail.com>
```

Based on that comment, `main` should be pointed at commit 5e39601 not 8c940c6

**Comment by djdembeck** [comment]
I suggest following the readme instructions on updating if you're having issues.

**Comment by urda** [comment]
There are no issues with the install, and that was never mentioned in this GitHub issue? Not sure how off track that got, but that's not the comment here.

The `README` details that a user should just do a `git pull`:

https://github.com/djdembeck/Audnexus.bundle/blob/8c940c6e674c97c5fb6e2b3482ce7d26f6f53501/README.md?plain=1#L62-L79

And normally if pointed at main, they would. But currently the `main` of this project isn't sticking to the tagged releases, and has advanced beyond `v1.3.0`

The original request was because **it is ambigious** how `main` is managed, and the fact that the `git log` shows `main` is out of sync of release can be a problem for users. They often do not want to deep dive into commits to see if anything is really impacted by `main` not being the actual release. This was demonstrated with the `git log` showing the desync. In this case it appears to just be a documentation thing, but what if in the future you or your contributors advanced `main` too far?

That's the issue.

**Comment by rabelux** [comment]
@urda: IMHO @djdembeck's workflow is totally fine and I wouldn't ask him to change anything. Functionality wise release and main are in sync and that's all what counts for the "customer". Remember this is a free 1-person-project so I wouldn't ask for workflows to always be 100% correct.

**Comment by urda** [comment]
> Precisely.
> 
> Getting hung up on a one line documentation change and equating this to breaking everyone's installation is a waste of my time.
> 
> I'm sorry if this is something you feel strongly about, but it's simply not worth the extra hassle.
> 
> I spent 8 hours straight working on a new feature yesterday, only to see this issue pop up. Do you understand how frustrating that is? Are you paying for the product? Are you contributing anything to the project?
> 
> There's enough GHI of people not even knowing how to add this plugin to plex, the last of my worries is the commit hierarchy.

This is disrespectful flat out.

---

> Getting hung up on a one line documentation change and equating this to breaking everyone's installation is a waste of my time.

I'm not. I raised an issue where the docs and state of the repo didn't sync up. I detailed it in full in this conversation which you can read. **[You also never responded to the actual issue, and glossed over it with a generic RTFM comment](https://github.com/djdembeck/Audnexus.bundle/issues/104#issuecomment-1603721873)**. The issue here raised is not negative and was clear in request.

> I'm sorry if this is something you feel strongly about, but it's simply not worth the extra hassle.

I'm sorry you are not responding to the meat of the issue here, and you think release managment "isn't worth the extra hassle".

> There's enough GHI of people not even knowing how to add this plugin to plex, the last of my worries is the commit hierarchy.

That's such poor customer treatment. The issues why an out of sync `main` from tagged releases was **[fully detailed here](https://github.com/djdembeck/Audnexus.bundle/issues/104#issuecomment-1603735673)** and brought to attention.


> I spent 8 hours straight working on a new feature yesterday, only to see this issue pop up. Do you understand how frustrating that is? 

That's great you chose to do that

> Are you contributing anything to the project?

Is this how you treat users bringing detailed issues to you for contribution?

> Getting hung up on a one line documentation change and equating this to breaking everyone's installation is a waste of my time.

Completely disrespectful when the issue raised here is a valid issue. And it's sad you think this is a waste of time when **you even claim on your own GitHub:**

https://github.com/djdembeck/djdembeck/blob/1826bc3ebc88354cd47ec0f0e68e71d239aa3f91/README.md?plain=1#L6

> 🤔 I’m looking for help with quality control of my projects.

That's apparently false.

**Comment by djdembeck** [comment]
> That's such poor customer treatment.

You received this code for free.

This is getting aggressive and out of hand, goodbye.
