### ISSUE TITLE
Language for Author Biopgraphy

### ISSUE THREAD

**Issue by try-and-error-and-repeat** [djdembeck/Audnexus.bundle#113]
I have the following problem. I wanted to enhance my audiobook library with the Audnexus Agent. It works well so far, but the description texts of the books are in German, which is as it should be. However, unfortunately, the texts about the authors are all in English. Did I make a mistake somewhere? Attached are a few screenshots, including an example.
![Screenshot 2024-01-09 194727](https://github.com/djdembeck/Audnexus.bundle/assets/71461694/43971940-b8f4-4c53-be33-9aa93c15b33e)
![Screenshot 2024-01-09 194754](https://github.com/djdembeck/Audnexus.bundle/assets/71461694/0604d897-d481-4450-8020-57558b5f732d)
![Screenshot 2024-01-09 194807](https://github.com/djdembeck/Audnexus.bundle/assets/71461694/38af90d0-2a1e-4361-aa0a-e895fcdf52c3)
![Screenshot 2024-01-09 194827](https://github.com/djdembeck/Audnexus.bundle/assets/71461694/35982699-8a76-4916-802e-ea0b583c4e45)
![Screenshot 2024-01-09 194837](https://github.com/djdembeck/Audnexus.bundle/assets/71461694/1562b970-ba81-4eff-8064-341950376061)
![Screenshot 2024-01-09 194843](https://github.com/djdembeck/Audnexus.bundle/assets/71461694/881e4a72-8d24-45a4-be5b-4c80151e463a)

**Comment by murmelbahn** [comment]
Hi, 
at least you get some Artist Bio. I just configured everything and sadly the artist bio is empty.

**Comment by djdembeck** [comment]
Thanks for the report! I found the issue was artist profiles were defaulting to US region. This should be fixed in 1.3.2
