### ISSUE TITLE
Fix Match search results truncated

### ISSUE THREAD

**Issue by b3nw** [djdembeck/Audnexus.bundle#118]
When searching for books with similar titles where the volume number is at the end, it is difficult to figure out which is the right volume. 

![image](https://github.com/djdembeck/Audnexus.bundle/assets/189466/16871b77-a486-4f8b-aa45-22489df2debf)

**Comment by djdembeck** [comment]
Yes this is intentional. You can either enter the ASIN for the book you want and search that, or guess based on author and year

**Comment by b3nw** [comment]
@djdembeck     why is it intentional to truncate the full book title?   guess based on author and year is pretty painful solution....
