### ISSUE TITLE
Supported languages

### ISSUE THREAD

**Issue by rabelux** [djdembeck/Audnexus.bundle#16]
Does the new plugin support other sites than audible.com? Like audible.de, .fr, ...

**Comment by mmuenker** [comment]
is there any news to this? This currently breaks the audiobookshelf book match feature: https://github.com/advplyr/audiobookshelf/issues/731#issuecomment-1159287313

**Comment by djdembeck** [comment]
It doesn't break anything, because it's not even a feature.

**Comment by baloodusudouest** [comment]
if this can help, for french for ex, seanap work on a files to find the information on the audible french information to put on the mp3tag
https://github.com/seanap/Plex-Audiobook-Guide/blob/master/mp3tag/data/sources/Audible.fr%23Search%20by%20Album.src

**Comment by djdembeck** [comment]
Pending upstream implementation then I can get to writing the plugin update: https://github.com/laxamentumtech/audnexus/pull/498

**Comment by rabelux** [comment]
Awesome! Appreciate it 😃

**Comment by Hoempi** [comment]
Great news, looking forward to it. Thank you very much!

**Comment by djdembeck** [comment]
Going well so far. Here's an author taken from `?region=de`:
```
{
    "asin": "B001JSF77S",
    "description": "Vom Radio-Unterhalter zum Autor von Psychothrillern – ein Kontrast, wie er sich auch in Sebastian Fitzeks Romanen entfaltet. Alltägliche Situationen entwickeln sich bei ihm zu düsteren Szenarien. Mit „Die Therapie“ gelang ihm 2006 der Durchbruch. Seitdem sind seine Krimis aus den deutschen Bestsellerlisten nicht mehr wegzudenken. 1971 in Berlin geboren, wurde Sebastian Fitzek 2016 als erster deutscher Autor mit dem renommierten „Europäischen Preis für Kriminalliteratur“ ausgezeichnet.Temporeiche Erzählweise Er bedient sich zahlreicher Cliffhanger, die seine packende Erzählweise an den Stil amerikanischer Thriller erinnern lässt. Als Ur - Berliner verlegt er seine Handlungen oft an Schauplätze in Berlin und macht das Grauen damit fast greifbar.Gänsehaut pur Das Erfolgsrezept für Fitzeks literarischen Nervenkitzel ist die Schocktherapie. Aus der Annahme eines Pakets für den Nachbarn oder einem gewöhnlichen Langstreckenflug entwickelt der Autor die Geschichte zu einer Art Worst - Case - Szenario.Er spielt dabei mit Urängsten wie der Verfolgungsangst oder dem Ausgeliefertsein– Themen, die gerade im Hörbuchformat für noch mehr Gänsehautfeeling sorgen.",
    "genres": [
        {
            "asin": "16209910031",
            "name": "Krimis & Thriller",
            "type": "genre"
        },
        {
            "asin": "16206595031",
            "name": "Kunst & Unterhaltung",
            "type": "genre"
        },
        {
            "asin": "16209739031",
            "name": "Literatur & Belletristik",
            "type": "genre"
        }
    ],
    "image": "https://images-na.ssl-images-amazon.com/images/S/amzn-author-media-prod/rjtjrte07nuucmkjhrc08rtst8.jpg",
    "name": "Sebastian Fitzek",
    "region": "de"
}
```

**Comment by djdembeck** [comment]
This is all ready to go upstream :partying_face: Will try to work on it some this week, as the agent needs a bit of an overhaul to handle searching in the other regions.

**Comment by djdembeck** [comment]
For anyone feeling adventurous, you can try the new region options in `feat-multi-region` and follow the PR for progress: https://github.com/djdembeck/Audnexus.bundle/pull/66

**Comment by djdembeck** [comment]
Multi region support is now live in the `develop` branch. I've only tested `[us]` and `[uk]` regions specifically, so please test it and see what happens :)

**Comment by Hoempi** [comment]
I have been using it via audiobookshelf for a while now. Works well for me with audible.de. Thanls for making it possible!

Sometimes it is strange that I do not find a German book using audible.de, but using the same author and title I do find it on audible.com. But I would attribute that to Amazon/Audible not being consisten. As with their ASINs, sometimes it is the same for .de and .com and sometimes it differs, even though it si the exact same edition.

**Comment by rubbishgee** [comment]
Thanks for doing this. as well with the develop branch and the feat-multi-region branch i don't have any results no matter what i type in and no matter what region i,m using.
