### ISSUE TITLE
using length to pick between abridged or not

### ISSUE THREAD

**Issue by TomW1605** [djdembeck/Audnexus.bundle#26]
i have had a few files be incorrectly matched as abridged and i was thinking that maybe you could use the length to help match to the right format. not sure if legacy plugins have access the right data about the media but if so it could help matching.

**Comment by djdembeck** [comment]
Yes, sadly The duration isn’t available via true agent. It’s probably possible to get that information directly, but that’s quite the project and not something I personally will take on (always open to PRs)

**Comment by TomW1605** [comment]
i thought that would be the case but no harm in checking
