### ISSUE TITLE
Fail to show up the agent

### ISSUE THREAD

**Issue by Haximaxi** [djdembeck/Audnexus.bundle#27]
After a reinstall off windows and then plex I tried to get the agent to show up again in plex but it does not work anymore

![unknown](https://user-images.githubusercontent.com/57035855/140530061-302772cd-4c90-4f52-8d1c-5672ea52eda7.png)
![unknown (1)](https://user-images.githubusercontent.com/57035855/140530094-777dc8d2-01fa-4e2c-aa1c-852d88b1ce0a.png)
)

I have followed the exact steps of the guides and it always worked until now, any idea what I am doing wrong ?

I restarted plex after the install

I run on the latest Plex Media server (as off today) and the latest W11 build

**Comment by rabelux** [comment]
From the referenced plex link:
"3. Bundles downloaded from GitHub will usually have extra identifiers appended to the bundle’s filename, such as “-master”. Edit the bundle’s file or folder name to remove any text after “.bundle”"

**Comment by Haximaxi** [comment]
i feel like a moron 

I did as you said and the agent still is not showing up in the agent list, but it is somehow working what i want it to do so not going to ask for more 

Thanks for the answer!
