### ISSUE TITLE
Audnexus not showing up in Artists Agents

### ISSUE THREAD

**Issue by nmillz** [djdembeck/Audnexus.bundle#38]
Installing this for the first time and followed your directions as well as seanap's for setting this plugin up.
After restarting the plex server, the Audnexus Agent is found under Albums/AudNexus Agent, but not Artists. 
Tested with both versions .27 and .28. Version .27 works and .28 does not.

**Comment by djdembeck** [comment]
The album and artist agent are from the same file. It’s impossible for one to be loaded and not the other. 

I cannot reproduce this.

**Comment by nmillz** [comment]
> 



> Did you follow this instruction: https://github.com/djdembeck/Audnexus.bundle#installing or this https://support.plex.tv/articles/201187656-how-do-i-manually-install-a-plugin/? it is working for me.

Both. I followed the Github instructions for .28 and the manual install for .27



> The album and artist agent are from the same file. It’s impossible for one to be loaded and not the other.
> 
> I cannot reproduce this.

If there's a way to post pictures, I could show you screenshots. My server is running on Ubuntu using docker to run Plex
