### ISSUE TITLE
Not getting agent to show on Unraid or Windows 10

### ISSUE THREAD

**Issue by pakiyabhai** [djdembeck/Audnexus.bundle#40]
HI, 
n00b alert , I've been trying to get audnexus agent to show up without much success . 

On Unraid , I'm putting the file inside 
/mnt/user/appdata/binhex-plexpass/Plex Media Server/Plug-ins

Owner is Root with  -rw-r--r-- permission but to no avail 

I then did a server install in Windows & installed the audnexus.bundle inside windows 
%LOCALAPPDATA%\Plex Media Server\Plug-ins

I also did library -> advance  and restarted my server couple of times , any help would be appreciated.

**Comment by pakiyabhai** [comment]
I was able to resolve the UnRaid problem by ssh and using git pull . 

How to do the same on windows ?

**Comment by rabelux** [comment]
Often people have incorrect naming of the plugin folder. It has to end with `.bundle`.
