### ISSUE TITLE
Plugin doesnt show

### ISSUE THREAD

**Issue by antonio59** [djdembeck/Audnexus.bundle#45]
I am trying to add the l;=plugin but it doesn't show in plex. I am curious if this could be due to plex no longer supporting plugins or if I did something wrong?

<img width="461" alt="Screenshot 2022-03-27 at 22 31 13" src="https://user-images.githubusercontent.com/9450209/160301874-c8575e5d-ab6a-46fe-9853-493360d0f104.png">

<img width="749" alt="Screenshot 2022-03-27 at 22 31 53" src="https://user-images.githubusercontent.com/9450209/160301897-a22b5531-62eb-41b6-a958-58de45dced4c.png">

**Comment by Juzziee** [comment]
Hey.

Same issue when using a docker container

**Comment by djdembeck** [comment]
It does not show under plugins. Please read the readme https://github.com/djdembeck/Audnexus.bundle#create-an-audiobook-library

**Comment by stubro13** [comment]
Just wanted to add for anyone else not seeing the agent. I also couldn't see the Audnexus agent until I closed my browser and navigated back to the Plex web app.
