### ISSUE TITLE
Bug? Wrong language fetched, when selecting language from Plex "Fix Match" Pulldown

### ISSUE THREAD

**Issue by gitttt54** [djdembeck/Audnexus.bundle#48]
Hello,

*I have read [this issue](https://github.com/djdembeck/Audnexus.bundle/issues/16) and understand, that no other language support than english works atm,
but the current bundle's behaviour is kind of cumbersome for the user, because it forced more manual work to change the language back to english from the wrong fetched language.

In Plex, the sumary for artist "Franz Kafka" was fetched in english language. I wanted to change this to german* languange, so I choosed "fix match" and selected "german" as language of my choice. After that, the sumary was fetched in spanish language.

If there exists no german sumary, I'd prefer english language over any other language,
can we have the bundle have fall-back to english language, if the choosen language is not available for sumary?

Having a language like spanish (or french...) might not be understandable by all users, so it might be better to fall back to english language.

EDIT: I tried fixing the artist sumary to english language again, but Plex is fetching spanish language again, so I can not get it back to english.

**Comment by djdembeck** [comment]
I’m not sure where the Spanish summary came from, since, as you noted, Audnexus only uses audible’s US (English) site.

**Comment by gitttt54** [comment]
I did not locked the summary field. I just expected to get the english summary when chosing english language to correct the spanish one.
Manually setting the language does not seem to work. 
The first time (after test library creation and scanning it) the summary for artist Franz Kafka was english. Now, it seems not possible to get it back to english anymore.

**Comment by gitttt54** [comment]
I did some further testings, but no change, unfortunately.
Initital scan of library (after creating and setting up with the audnexus bundle) works fine: english artists summaries are fetched.
If I try to change any artists summary to another language, then spanish is fetched and can not be corrected to any other language.

So don't touch the "fix match" button... :-D

**Comment by djdembeck** [comment]
There are 2 'Franz Kafka' currently in Audnexus, one with the Spanish summary you mention. For me, the one with a score of 100 is the English summary. Selecting a different language from the dropdown does nothing, so I'll remove them.
