### ISSUE TITLE
Refresh Metadata Doesn't Update Artist After Metadata Update

### ISSUE THREAD

**Issue by Ritter99** [djdembeck/Audnexus.bundle#54]
I have several audiobooks that have incorrect metadata. After initial import, I used Picard to update the incorrect metadata so it would match properly. After a "Refresh Metadata" in Plex, the book correctly matches but leaves the author field untouched (and incorrect).

If I remove the file(s) from Plex and place them back in, the book and author correctly match. 

Is this a bug, or is there something I can do to make the authors match correctly on refresh?

**Comment by rabelux** [comment]
From my experience you have to do a rescan of files instead of refreshing metadata. Which makes sense if local metadata is preferred.

**Comment by djdembeck** [comment]
Since this is a metadata agent and not a scanner, we don't control how files are interpreted or changed. Audnexus just matches what the scanner passes.
