### ISSUE TITLE
Update covers

### ISSUE THREAD

**Issue by garlik82** [djdembeck/Audnexus.bundle#58]
Any way to get audnexus API to update book covers?

Thanks in advance.

**Comment by djdembeck** [comment]
Yes. You can add `update=1` to the audnexus URL of the book you want to update. Updates are allowed every 24hr per item.

**Comment by garlik82** [comment]
Is it instantaneous or does it take some time?

**Comment by djdembeck** [comment]
It should take less than 5 seconds.

**Comment by garlik82** [comment]
I must be doing something wrong than. I tried updating the harry potter books cover but it’s still the same.

**Comment by djdembeck** [comment]
What is the ASIN?

**Comment by garlik82** [comment]
It's working on the API side but Plex still not pulling the updated cover. B00WX7Y0W2

**Comment by djdembeck** [comment]
It looks like it pulls in the new art:
```
2022-09-05 15:07:09,335 (148860bcdb38) :  DEBUG (networking:143) - Requesting 'https://api.audnex.us/books/B00WX7Y0W2'
2022-09-05 15:07:09,386 (148860bcdb38) :  DEBUG (networking:143) - Requesting 'https://m.media-amazon.com/images/I/8174SXcBn+L.jpg'
2022-09-05 15:07:09,574 (148860bcdb38) :  DEBUG (networking:175) - Not caching 'https://m.media-amazon.com/images/I/8174SXcBn+L.jpg' (content type 'image/jpeg' not cacheable in Agent plug-ins)
```

That being said, it is not set as the default. Is that the behaviour you are expecting?

**Comment by garlik82** [comment]
I still can't get the new artwork in Plex. where can I get audnexus.bundle logs in Plex?

**Comment by djdembeck** [comment]
Try version `0.4.1` now in `develop`:
https://github.com/djdembeck/Audnexus.bundle/commit/bdb92b0a8fbca894a86ab67d830bebbabf811be9

FLog files here: https://support.plex.tv/articles/201106148-channel-log-files/

**Comment by garlik82** [comment]
Yep I had to manually select the image. running 0.4.1.

**Comment by djdembeck** [comment]
Cloudflare caches pages for 24hrs. From the time you updated to Cloudflare updating can vary.

**Comment by garlik82** [comment]
Been using ?update=1 and most of the ASIN I try never get updated. Tried books and authors. Am I not doing it right?

**Comment by djdembeck** [comment]
Items will now update every 30 days on their own.

**Comment by theiamdude** [comment]
> It looks like it pulls in the new art:
> 
> ```
> 2022-09-05 15:07:09,335 (148860bcdb38) :  DEBUG (networking:143) - Requesting 'https://api.audnex.us/books/B00WX7Y0W2'
> 2022-09-05 15:07:09,386 (148860bcdb38) :  DEBUG (networking:143) - Requesting 'https://m.media-amazon.com/images/I/8174SXcBn+L.jpg'
> 2022-09-05 15:07:09,574 (148860bcdb38) :  DEBUG (networking:175) - Not caching 'https://m.media-amazon.com/images/I/8174SXcBn+L.jpg' (content type 'image/jpeg' not cacheable in Agent plug-ins)
> ```
> 
> That being said, it is not set as the default. Is that the behaviour you are expecting?

I'm seeing similar logs in m y setup and i am facing the same issue. I believe I am using the latest version with plex on docker.

Is there any config required to fix this?
