### ISSUE TITLE
Manual search displays author and narrator names incorrectly

### ISSUE THREAD

**Issue by plmcgrn** [djdembeck/Audnexus.bundle#59]
When doing a manual match, the search results incorectly display the author initials.
Example:
```
Recursion by Blake Crouch and narrated by Jon Lindstrom
```
Is displayed as
`"Recursion" by B.C.Crouch w/ J.L.Lindstrom`

Expected
`"Recursion" by B. Crouch w/ J. Lindstrom`

This is probably a straightforward fix, if a string split is done on `' '`, to isolate the surname from the given name/initials/etc., before doing the string manipulation to work on authors that use initials instead of a given name.  I may do a PR if I'm feeling ambitious, though Python isn't my normal comfort zone.

**Comment by rabelux** [comment]
This seems to be caused by commit 15e377b484e8ccbab00465456717c83d677fd8dc. @djdembeck why did you introduce `enumerate` if you're not using `index` ? [Line 97 in search_tools.py](https://github.com/djdembeck/Audnexus.bundle/blame/main/Contents/Code/search_tools.py#L97)

**Comment by djdembeck** [comment]
> This seems to be caused by commit [15e377b](https://github.com/djdembeck/Audnexus.bundle/commit/15e377b484e8ccbab00465456717c83d677fd8dc). @djdembeck why did you introduce `enumerate` if you're not using `index` ? [Line 97 in search_tools.py](https://github.com/djdembeck/Audnexus.bundle/blame/main/Contents/Code/search_tools.py#L97)

I believe at the time I was using enumerate for multiple things, and never realized I wasn't needing an index in this case.
