### ISSUE TITLE
Artist Matching

### ISSUE THREAD

**Issue by zacm1979** [djdembeck/Audnexus.bundle#69]
I keep running into a weird issue for Artist matching. There are some instances where the artist has an audible entry, but no combination of the name actually pulls it up when searching from the match window. Since authors have an ASIN also I have even tried using it in combination with the name.

Example:

Craig Schrader
www.audible.com/author/Craig-Schrader/B09K4JPXP5
(Book that populated the artist) https://www.audible.com/pd/SuperDrunk-Audiobook/B09QKS71CR

The only match it finds has a score of 46
Craig Schaefer
www.audible.com/author/Craig-Schaefer/B00JYJPVG6

**Comment by djdembeck** [comment]
`Craig Schrader` finds the correct result in both plex and the API
