### ISSUE TITLE
Colon in filename not working well

### ISSUE THREAD

**Issue by MoSattler** [djdembeck/Audnexus.bundle#73]
The guide says that the files should be named in this schema:
> Book Name: Subtitle.m4b

But in some systems this is causing problems:

MacOS
<img width="255" alt="Screenshot 2023-01-01 at 16 51 48" src="https://user-images.githubusercontent.com/64152453/210176862-e6062267-5769-4b28-86a1-caafde48ed6b.png">

Synology NAS
<img width="650" alt="Screenshot 2023-01-01 at 16 51 16" src="https://user-images.githubusercontent.com/64152453/210176850-ea571c79-b9dd-4edb-b3c6-80207e9fc15b.png">

**Comment by djdembeck** [comment]
This is not a strict requirement but a best practice. You can, of course, modify per your system as needed.
