### ISSUE TITLE
Matching but no Metadata?

### ISSUE THREAD

**Issue by tdk1069** [djdembeck/Audnexus.bundle#75]
Hi, I think I am doing something wrong :D 
I have a test Audio Book I am trying to get info on and struggling. It matches, and if I do Fix Match and search via the agent it finds the book (I'm assuming it is this agent finding it as the result name matches the doc "TITLE" by AUTHOR_FIRSTINITIAL.AUTHOR_LASTNAME w/ NARRATOR_FIRSTINITIAL.NARRATOR_LASTNAME @ 100%".

When I select it on fix, or refesh meta data it goes off and spins the spinner for a while. Basic info such as author/title come back (In my instance "Foxglove Summer" by B.Aaronovitch w/ K.Holdbrook-Smith) but there's nothing else. no cover, description, tags etc.

I am not sure where to look for information to diagnose, I downloaded my plex server logs but couldn't find any entry to do with this particular agent.

**Comment by djdembeck** [comment]
Try to refresh it, there was a server problem yesterday.

**Comment by tdk1069** [comment]
Hi, 
Thanks. I did try this morning and one book got populated, but then following books didn't. Again pulling in the formatted title but no extra data

**Comment by tdk1069** [comment]
Might be the book? I did another one after this one. Trouble one is "Moon over soho" I've tried ASIN B009CZN2AE and B005CW3NN2

**Comment by djdembeck** [comment]
Both of those ASINs look fine in the API. I did just improve the server response time dramatically today, so it could still have been timing out.
