### ISSUE TITLE
No Match if author has initials

### ISSUE THREAD

**Issue by question69** [djdembeck/Audnexus.bundle#79]
I'm using Audnexus.bundle since v0.4.1 and it's working great so far, except one problem i can't seem to fix even after the latest two updates.

If the Author has initials in his name, I can't match the audiobook at all. Out of 250 audiobooks i have 15 unmatched and everyone of those is by an author with initials. 
All files were structured and tagged using Seanaps guide and he has no problem matching authors with initials, updating and reinstalling the bundle didn't help.

Example authors:
C Z Dunn
C. L. Werner
Justin D. Hill

**Comment by djdembeck** [comment]
Thank you for bringing this up. I was able to narrow down and fix the cause.
