### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by seanap** [djdembeck/Audnexus.bundle#8]
Can we have the agent write the title + subtitle to plex?  There are a few series that don't play nice, specifically https://www.audible.com/series/Chaos-Seeds-Audiobooks/B072YW73X4

![image](https://user-images.githubusercontent.com/17012946/135923641-83f91e9f-1a88-4bfa-bbeb-667ff12406dc.png)

When doing a match the full title is displayed

![image](https://user-images.githubusercontent.com/17012946/135923883-d8bfa7ee-503c-4087-b901-71cd46aeef00.png)

**Comment by seanap** [comment]
Figured out the issue.  When Local Media Assets are above Audnexus then it is using the file name.  Once I moved Audnexus up then the full title gets written

**Comment by djdembeck** [comment]
It’s certainly worth looking into showing both though. In some cases this would be quite a long string however

**Comment by seanap** [comment]
Since I know the files are tagged right moving the agent to the top spot can make the occasional mismatches hard to find
