### ISSUE TITLE
Match with ASIN don't work for me

### ISSUE THREAD

**Issue by elconcu** [djdembeck/Audnexus.bundle#81]
I'm trying to match with the ASIN the books that I can't find with the name, but the result is this:
![1](https://user-images.githubusercontent.com/124478856/216799259-1013e384-85bb-450e-9bf7-5a899b189258.png)
![2](https://user-images.githubusercontent.com/124478856/216799302-002fb10d-08ef-496d-b8bd-1d01c1f5a32a.png)
It´s appear like matched but without any metadata, and the name is the ASIN_region. I tried to use with other region and the same result. And it happen with all the books i tried.
I use it on windows.

I find another problem to match, but i can resolve doing it manually: - When the title have an accent mark or a ñ it don´t work. Example: "el último capo" i must write "el ultimo capo" or "Mañana azul"by pierce brown, i must write "Manana azul".

**Comment by djdembeck** [comment]
That asin doesn't look to exist: https://api.audible.es/1.0/catalog/products/B0924SRH3Y?response_groups=always-returned,product_extended_attrs,product_attrs,series
