### ISSUE TITLE
Quick Match not Working with ASIN's

### ISSUE THREAD

**Issue by LeLawnGames** [djdembeck/Audnexus.bundle#82]
No matter what I do the quick match function isn't working for my library and I'm forced to go through and individually match each title. Has there been any official fix for this or new approach suggested?

Currently I've used the technique I read about here of naming the book folder "Book Name_ASIN"

My folder structure is Author Name > Book Name_ASIN > Book Name.m4b (or mp3's for a few titles, it happens to books in both formats)

I'd really appreciate any pointers or help as I'm feeling pretty lost as to how to fix this issue and I've got a pretty large collection which makes manually doing it really not a great solution.

**Comment by djdembeck** [comment]
What happens if you use 

```
Book Name/B01234ABCD_Book Name: Subtitle.m4b
```
Or another variant of it being in filename?

If you could also switch the AGENT log level to DEBUG, add 1 book, scan, and attach the logs.

**Comment by mr-neoterix** [comment]
I think I have the same problem. The Quick Match seems to recognise the correct ASIN, but then it assigns a generic audiobook from 1969 without metadata, which always has the name in the form <ASIN>_<Language ISO Code>.
<img width="1162" alt="Bildschirm­foto 2023-02-23 um 15 52 57" src="https://user-images.githubusercontent.com/1035129/220943097-7f25db40-4f31-49e7-a86e-aa62f7ea7221.png">

**Comment by LeLawnGames** [comment]
Adding the ASIN at the start so that the new folder names read "ASIN_BOOKNAME" seems to have done the trick, I needed to readd all the books that we're properly matched but now it's quick matching. Will keep updated if I run into any more of the unmatching issues but as of now I think that fixed it. Thank you @djdembeck ! @mr-neoterix perhaps try that and see if it helps.

**Comment by mr-neoterix** [comment]
Ok, then I guess I have another problem. I had already named my files exactly like this with this ASIN.

**Comment by djdembeck** [comment]
I discovered a bug around this, please try version `1.2.0` and see if the issue is resolved.

**Comment by LeLawnGames** [comment]
That fix actually didn't end up working and now I'm back to square one except now I can't even manually match anything. It's all showing up as ASIN_us or not showing any match at all even when I try to manually search the title. Attaching log reports, set it to DEBUG and added a single new book.

The weird thing that happened when I added the new book is originally it matched perfectly, but then it reverted to removing all of the added metadata, removing the title and reverting to ASIN_us. Which makes me think it's initially working but then there's some bug that's unmatching it? Or perhaps it's something in my setup? Any help appreciated!
[com.plexapp.agents.audnexus.log](https://github.com/djdembeck/Audnexus.bundle/files/10829896/com.plexapp.agents.audnexus.log)

**Comment by djdembeck** [comment]
> That fix actually didn't end up working and now I'm back to square one except now I can't even manually match anything. It's all showing up as ASIN_us or not showing any match at all even when I try to manually search the title. Attaching log reports, set it to DEBUG and added a single new book.
> 
> The weird thing that happened when I added the new book is originally it matched perfectly, but then it reverted to removing all of the added metadata, removing the title and reverting to ASIN_us. Which makes me think it's initially working but then there's some bug that's unmatching it? Or perhaps it's something in my setup? Any help appreciated! [com.plexapp.agents.audnexus.log](https://github.com/djdembeck/Audnexus.bundle/files/10829896/com.plexapp.agents.audnexus.log)

Your logs seem to indicate an artist (author) isn't matched and can't be loaded. This is probably the bug I fixed above. I am assuming it's the author for the book you are trying to add, `Yuval Noah Harari`

Are you talking about `ASIN_us` showing in search results? If yes, that's intended and telling you quick match worked, you have to click it.

**Comment by LeLawnGames** [comment]
Oh yes that worked. Thanks!
