### ISSUE TITLE
Option to use local tags for Mood & Style (Series/Author/Narrator)?

### ISSUE THREAD

**Issue by manalive** [djdembeck/Audnexus.bundle#83]
For whatever reason, this is one piece of metadata that Audible gets wrong more often than it gets right, at least in my library:

- Books in a series not listed as part of a series
- Some books are listed as being in a series; others in the same series with no series
- Books in a series listed as being in different series (usually formatting discrepancies)

I've set up all the Series tags from seanaps guide but Audnexus seems to use whatever Audible has and doesn't generate Mood tags from them. If I manually add the Mood tags they are not used in Plex either.

pretty please allow for overriding series info with the tag data and generate the mood tags. This would also take care of non-audible audiobooks that are in a series.

**Comment by baloodusudouest** [comment]
Hi,

Same for me, the series are not picked up from audible too

**Comment by manalive** [comment]
Actually, I realize it's ALL of the stuff that gets put into Mood and Style tags, not just the Series.

Here is an example of an author/composer who is listed several different ways on audible

- Professor Timothy B. Shutt
- Prof. Timothy Shutt
- Timothy B. Shutt
- Timothy Baker Shutt

This isn't just on different books, either. This is the same person listed differently as the Author and Narrator of the same book. 

I have it fixed in the tags of course, but that is only used for the Album Artist and Artist tags. The Mood and Style tags are taken from Audible so they are all messed up.

**Comment by djdembeck** [comment]
As far as I'm aware, Plex never exposed ID3 tags to external agents. If someone knows better I can gladly add this.
