### ISSUE TITLE
Previously Matched Titles Are Becoming Unmatched

### ISSUE THREAD

**Issue by LeLawnGames** [djdembeck/Audnexus.bundle#85]
I have two issues occurring. First of all the quick match doesn't work ever even after following all the previous discussions in past issues.

The second, and title of this issue, is that even after I spend my time going through and manually matching titles, they will randomly unmatch with zero pattern to follow.

I'd really love some guidance from anyone who's gotten this whole setup to work in a stable manner as it at least seems to me like it's impossible to get this to a level of usability that's worth the work.

**Comment by djdembeck** [comment]
What are you using for quick match? File name or manual entry? And what is the string you are trying?

At what point do titles become unmatched? Library scans, refreshes, etc? I have an extensive library and have 0 become unmatched since the writing of this plugin.

**Comment by LeLawnGames** [comment]
Referenced this issue and shared logs here: https://github.com/djdembeck/Audnexus.bundle/issues/82#issuecomment-1444805813
