### ISSUE TITLE
Series not working anymore

### ISSUE THREAD

**Issue by baloodusudouest** [djdembeck/Audnexus.bundle#88]
Hi,

The series are not put on the plex metadata for all the series i have (lord of the rings, harry potter...)
I'm using the french version of the audiobook,  maybe it's the reason why?

Does anyone have the same problem? For US or for other country?

Thanks

**Comment by plmcgrn** [comment]
Can confirm same issue on English US config.  All my series mood tags are gone, and that triggered Plex Meta Manager to wipe out the collections.  I think this happened after the most recent updates in v1.2.0.

When looking at the API call, it seems this info (seriesPrimary) is no longer in the response.  Example 
https://api.audnex.us/books/B01N48VJFJ?region=us

**Comment by djdembeck** [comment]
Thanks for the report. @plmcgrn beat me to it in finding the bug. Tags (moods/styles) were being cleared after setting them, thus having no effect.

I've released a fixed version of the plugin for this.
