### ISSUE TITLE
Plugin is installed but I am not able to actually use it

### ISSUE THREAD

**Issue by Saval-0** [djdembeck/Audnexus.bundle#91]
I installed the plugin normally and it shows up in the agent drop down menu. But if I go ahead and select it and than save the changes it doesn't allow me it says that the changes could not be saved.

Does someone have an idea on how to fix this problem?

**Comment by zdaar** [comment]
I have the same issue

**Comment by djdembeck** [comment]
https://github.com/djdembeck/Audnexus.bundle/issues/50

**Comment by popeye2468** [comment]
this is fixed by renaming the library it must ba called
Audiobooks
and not
AudioBooks

**Comment by djdembeck** [comment]
The library name can be anything.
