### ISSUE TITLE
Searching in "Fix Match" isn't working

### ISSUE THREAD

**Issue by pjgreen88** [djdembeck/Audnexus.bundle#95]
Seems like I can't search for titles via the "Fix Match" function anymore, although I did it previously. Hitting search immediately returns the "no matches found" no matter what fields are empty/filled.

**Comment by CharlesBassFF** [comment]
I am having the same issue. It’s not returning anything and doesn’t look like it’s searching for anything.

**Comment by akaep** [comment]
Still an issue. Immediately returns "No matches found". Any updates on this?

**Comment by 0dysseus** [comment]
This is occuring for me also. When I import new books, they are not matched. When I try to do so manually (also when trying to re-match existing books), I immediately get the "no matches found" message.

**Comment by popeye2468** [comment]
same for me too

**Comment by cerinawithasea** [comment]
I feel like for about a week none of my audiobooks seem to getting matched even though they are tagged well and the manual search seems to not be searching just immediately giving up.
Thanks for how well its worked before, I am a little lost now and that speaks volumes

**Comment by romanoh** [comment]
> Seems like I can't search for titles via the "Fix Match" function anymore, although I did it previously. Hitting search immediately returns the "no matches found" no matter what fields are empty/filled.

the fix match is working for me:
https://i.imgur.com/HWzxCtu.png
do you have the latest version?

**Comment by djdembeck** [comment]
This sounds like a bug in previous versions: https://github.com/djdembeck/Audnexus.bundle/issues/92

If you are not running v1.2.2, please update

**Comment by naandrade** [comment]
This is also happening to me even with v1.2.2

**Comment by djdembeck** [comment]
> This is also happening to me even with v1.2.2

Can you provide logs of this issue happening then?

**Comment by CharlesBassFF** [comment]
I would like to provide data.

What logs do you want to see?

**Comment by CharlesBassFF** [comment]
Can I DM on here?

**Comment by popeye2468** [comment]
it could be a plex issue because neither this one or the old one work and they did before, hopefully someone can get it working again.  If it helps im on latest Beta

**Comment by epaka3** [comment]
> it could be a plex issue because neither this one or the old one work and they did before, hopefully someone can get it working again. If it helps im on latest Beta

Think it’s a Plex issue. A lot of people having similar problems since upgrading to server version 1.32.0.6918.

**Comment by djdembeck** [comment]
FWIW, I am on 6918. If y'all can post some logs that would help see where it's coming from. run `tail -f PATH/TO/CONFIG/Library/Application\ Support/Plex\ Media\ Server/Logs/PMS\ Plugin\ Logs/com.plexapp.agents.audnexus.log` then attempt to fix match

**Comment by akaep** [comment]
Running 6918 on Windows 10 and Aud 1.2.2.

[com.plexapp.agents.audnexus.log](https://github.com/djdembeck/Audnexus.bundle/files/11243185/com.plexapp.agents.audnexus.log)

Let me know if you need any other logs! Thanks!

**Comment by CharlesBassFF** [comment]
My log is very similar to that one.

**Comment by djdembeck** [comment]
This is related to the SSL update Plex Media Server recently released:

https://forums.plex.tv/t/ssl-became-broken-after-latest-pms-update/837416/4

https://forums.plex.tv/t/plex-media-server-1-32-0-6918-custom-certificate-must-be-regenerated-with-new-openssl-arguments/837643

**Comment by CharlesBassFF** [comment]
Is there a guide to remedy this for Windows?

**Comment by CharlesBassFF** [comment]
Note down your current Plex Server software version, should be the broken -6918

Stop Plex Server using its tray icon.

Uninstall Plex Server with the regular ‘Apps’ control panel of Windows. Do not use 3rd party ‘uninstaller’ software like Revo etc. Do not use Registry cleaners/optimizers.

Go to your Plex data folder: %localappdata%/Plex Media Server/Updates/1.31.3.6886/packages/PMS1.31.3.6886.exe

Execute the installer for the previous software version

**Comment by akaep** [comment]
> Note down your current Plex Server software version, should be the broken -6918
> 
> Stop Plex Server using its tray icon.
> 
> Uninstall Plex Server with the regular ‘Apps’ control panel of Windows. Do not use 3rd party ‘uninstaller’ software like Revo etc. Do not use Registry cleaners/optimizers.
> 
> Go to your Plex data folder: %localappdata%/Plex Media Server/Updates/1.31.3.6886/packages/PMS1.31.3.6886.exe
> 
> Execute the installer for the previous software version

Yep, downgrading to 1.31.3.xxxx worked for me. Thanks for the quick instruction!

**Comment by ladypercy1** [comment]
The PMS downgrade work-around only works if you didn't upgrade PMS more than once.  PMS only keeps the last three upgrades on file.  So for me, I cannot use the downgrade work-around since the last known PMS that works with Audnexus is gone. 

Also, are Audnexus users never going to be upgrade their PMS going forward?

**Comment by djdembeck** [comment]
Commented this on another issue, putting it here too: This has been fixed in the latest Beta PMS for Windows, probably in public soon: https://reddit.com/r/PleX/comments/12yq6rm/new_beta_pms_version_available_1321699991e1e2e2c/

**Comment by akaep** [comment]
Great news. In the meantime, I have the 1.31.3.68XX installer if anyone needs to downgrade. PM me.
