### ISSUE TITLE
Audnexus Plugin on Plex Not Showing and Unable to Fix Matches

### ISSUE THREAD

**Issue by a-chakroun** [djdembeck/Audnexus.bundle#96]
**Issue**:
I am having trouble with the Audnexus plugin on Plex. The plugin is not showing up in the list, but it is detecting books on my pc, and I am unable to fix matches manually. I've already tried several troubleshooting steps, but the issue persists.

**Environment**:

Plex Media Server version:  Version 4.100.1
Operating system: Windows 10
Audnexus plugin version: v1.2.2

**Troubleshooting Steps Already Taken:**

Verified the installation and placement of the Audnexus.bundle in the correct directory.
Restarted Plex Media Server multiple times.
Checked Plex logs for any error messages related to the plugin.
Enabled the Audnexus agent for the specific library.
Attempted manual match fixes with the Audnexus agent selected.
Tried using alternative metadata agents such as Plex Music and Last.fm.
Cleared the agent cache and restarted Plex.
Updated Plex Media Server to the latest version.
Despite all these steps, I am still unable to find any matches when performing a manual match. I'd appreciate any assistance or guidance in resolving this issue.

![image](https://user-images.githubusercontent.com/24650722/232608973-3eb068d1-7794-425b-bcb4-e56c5fe17554.png)

![image](https://user-images.githubusercontent.com/24650722/232609040-40831788-681c-4d63-b16b-3b1f0de6f3bb.png)

Whatver I do, matching don't work, and I always have "No matches found."

**Comment by a-chakroun** [comment]
Yes it is, thank you!

**Comment by popeye2468** [comment]
so the fix for this is to downgrade plex? is a proper solution planned?

**Comment by djdembeck** [comment]
This has been fixed in the latest Beta PMS for Windows, probably in public soon: https://reddit.com/r/PleX/comments/12yq6rm/new_beta_pms_version_available_1321699991e1e2e2c/
