### ISSUE TITLE
Plug-in fully degraded by Plex - 100% not functioning

### ISSUE THREAD

**Issue by ladypercy1** [djdembeck/Audnexus.bundle#97]
Some 4-5 years ago, Plex announced Plug-ins were going to be deprecated and eventually, all plug-ins would need to update to the new API or they would stop working.

The first evidence we saw of this was when “Channels” was removed from the Plex/Web browser. All those plug-ins were removed.

As time marched forward, the new scanner and matcher agents, now written in C++ further minimized any need for Python (what plug-in scrapers rely on).

This type ‘no longer works’ behavior is expected.

It can be remedied by the plug-in developer updating the Plug-in to be compliant with the new API.

**Comment by djdembeck** [comment]
I have no clue what this issue is trying to say.  Plug ins are still enabled in PMS.

**Comment by ladypercy1** [comment]
Audnexus no longer works for me in PMS. I posted about this on Plex Forum, and a Plex employee replied, to which i copied and pasted  here above.

**Comment by epaka3** [comment]
Yep, I haven’t been able to upgrade my server without breaking Audnexus. @djdembeck Any idea what Plex changed to cause the breakage?

**Comment by ladypercy1** [comment]
I cannot even roll back to a version of PMS in which Audnexus works because too many updates have already happened.

**Comment by djdembeck** [comment]
This is a duplicate issue: https://github.com/djdembeck/Audnexus.bundle/issues/95
